# Create a Numpy ndarray object

Numpy is used to work with arrays. The object in numpy is called **ndarray**.

We can create Numpy **_ndarray_** using the **_array() function_**.

In [1]:
import numpy as np

arr = np.array([1,2,3,4])

print(arr)         # print the array

print(type(arr))   # print the type of array


[1 2 3 4]
<class 'numpy.ndarray'>


To create an ndarray, we can pass a __list__, __tuple__, or any array like object into __array() function__  
and it will converted into an ndarray.

### Example

Use a tuple to create an ndarray

In [2]:
arr = np.array((1,2,3,4))

print(arr)

print(type(arr))

[1 2 3 4]
<class 'numpy.ndarray'>


# Dimensions in array

A dimension in arrays is one level of array depth (nested arrays).  

nested array: are arrays that have arrays as their elements.  

## 0-D array

0-D arrays or **Scalars** are the elements in the array. Each value in an array is a 0-D array.

* Example :

In [4]:
arr = np.array(13)

print(arr)

print(type(arr))

13
<class 'numpy.ndarray'>


##  1-D array

An array that has 0-D array as its elements is called uni-dimensional or 1-D array

* Example :

In [6]:
arr = np.array([1,2,3,4])

print(arr)

print(type(arr))

[1 2 3 4]
<class 'numpy.ndarray'>


## 2-D array

An array that has 1-D array as its element is called a 2-D array.  

They are often used to represent a matrix.

* Example

In [9]:
arr = np.array([
                [1,2,3,4], 
                [5,6,7,8]
              ])

print(arr)

print(type(arr))

[[1 2 3 4]
 [5 6 7 8]]
<class 'numpy.ndarray'>


## 3-D array

An array that has 2-D array (matrix) as its element is called 3-D array

* Example :

In [10]:
arr = np.array([[[1,2,3],[4,5,6]], [[7,8,9],[10,11,12]]])

print(arr)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


# Checking the dimension of array

Numpy array provide **ndim** attribute that returns an integer value that tell us about the dimension of array

In [12]:
a = np.array(13)
b = np.array([1,2,3,4])
c = np.array([[1,2,3,4],[5,6,7,8]])
d = np.array([[[1,2,3],[4,5,6]], [[7,8,9],[10,11,12]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


## Creating higher dimension array

An array can have any number of dimensions.

When the array is created, you can define the number of dimensions by using the **ndmin** argument.

* Example :

In [13]:
arr = np.array([1,2,3,4], ndmin = 6)

print(arr)

print("Dimension of array is :",arr.ndim)

[[[[[[1 2 3 4]]]]]]
Dimension of array is : 6


# Thank You !!!!